import images from '../utils/imageloader';

const post1 = {
  id: 1,
  title: 'Test',
  desc: 'This is a brief description',
  content: `
The foregoing considerations bring an important question to the fore: what, according to Heidegger, is so special about human beings as such? Here there are broadly speaking two routes that one might take through the text of Being and Time. The first unfolds as follows. If we look around at beings in general—from particles to planets, ants to apes—it is human beings alone who are able to encounter the question of what it means to be (e.g., in moments of anxiety in which the world can appear meaning-less, more on which later). More specifically, it is human beings alone who (a) operate in their everyday activities with an understanding of Being (although, as we shall see, one which is pre-ontological, in that it is implicit and vague) and (b) are able to reflect upon what it means to be. This gives us a way of understanding statements such as “Dasein is ontically distinguished by the fact that, in its very Being, that Being is an issue for it” (Being and Time 4: 32). Mulhall, who tends to pursue this way of characterizing Dasein, develops the idea by explaining that while inanimate objects merely persist through time and while plants and non-human animals have their lives determined entirely by the demands of survival and reproduction, human beings lead their lives (Mulhall 2005, 15). In terms of its deep ontological structure, although not typically in terms of how it presents itself to the individual in consciousness, each moment in a human life constitutes a kind of branch-point at which a person ‘chooses’ a kind of life, a possible way to be. It is crucial to emphasize that one may, in the relevant sense, ‘choose’ an existing path simply by continuing unthinkingly along it, since in principle at least, and within certain limits, one always had, and still has, the capacity to take a different path. (This gives us a sense of human freedom, one that will be unpacked more carefully below.) This can all sound terribly inward-looking, but that is not Heidegger's intention. In a way that is about to become clearer, Dasein's projects and possibilities are essentially bound up with the ways in which other entities may become intelligible. Moreover, terms such as ‘lead’ and ‘choose’ must be interpreted in the light of Heidegger's account of care as the Being of Dasein (see later), an account that blunts any temptation to hear these terms in a manner that suggests inner deliberation or planning on the part of a reflective subject. (So perhaps Mulhall's point that human beings are distinctive in that they lead their lives would be better expressed as the observation that human beings are the nuclei of lives laying themselves out.)

The second route to an understanding of Dasein, and thus of what is special about human beings as such, emphasizes the link with the taking-as structure highlighted earlier. Sheehan (2001) develops just such a line of exegesis by combining two insights. The first is that the ‘Da’ of Da-sein may be profitably translated not as ‘there’ but as ‘open’. This openness is in turn to be understood as ‘the possibility of taking-as’ and thus as a preintellectual openness to Being that is necessary for us to encounter beings as beings in particular ways (e.g., practically, theoretically, aesthetically). Whether or not the standard translation of ‘Da’ as ‘there’ is incapable of doing justice to this idea is moot—one might express the same view by saying that to be Dasein is to be there, in the midst of entities making sense a certain way. Nevertheless, the term ‘openness’ does seem to provide a nicely graphic expression of the phenomenon in question. Sheehan's second insight, driven by a comment of Heidegger's in the Zollikon seminars to the effect that the verbal emphasis in ‘Da-sein’ is to be placed on the second syllable, is that the ‘sein’ of ‘Da-sein’ should be heard as ‘having-to-be’, in contrast with ‘occasionally or contingently is’. These dual insights lead to a characterization of Dasein as the having-to-be-open. In other words, Dasein (and so human beings as such) cannot but be open: it is a necessary characteristic of human beings (an a priori structure of our existential constitution, not an exercise of our wills) that we operate with the sense-making capacity to take-other-beings-as.

The two interpretative paths that we have just walked are not necessarily in conflict: in the words of Vallega-Neu (2003, 12), “in existing, Dasein occurs… as a transcending beyond beings into the disclosure of being as such, so that in this transcending not only its own possibilities of being [our first route] but also the being of other beings [our second route] is disclosed”. And this helps us to grasp the meaning of Heidegger's otherwise opaque claim that Dasein, and indeed only Dasein, exists, where existence is understood (via etymological considerations) as ek-sistence, that is, as a standing out. Dasein stands out in two senses, each of which corresponds to one of the two dimensions of our proposed interpretation. First, Dasein can stand back or ‘out’ from its own occurrence in the world and observe itself (see e.g., Gelven 1989, 49). Second, Dasein stands out in an openness to and an opening of Being (see e.g., Vallega-Neu 2004, 11–12).

As we have seen, it is an essential characteristic of Dasein that, in its ordinary ways of engaging with other entities, it operates with a preontological understanding of Being, that is, with a distorted or buried grasp of the a priori conditions that, by underpinning the taking-as structure, make possible particular modes of Being. This suggests that a disciplined investigation of those everyday modes of engagement on the part of Dasein (what Heidegger calls an “existential analytic of Dasein”) will be a first step towards revealing a shared but hidden underlying meaning of Being. Heidegger puts it like this:

whenever an ontology takes for its theme entities whose character of Being is other than that of Dasein, it has its own foundation and motivation in Dasein's own ontical structure, in which a pre-ontological understanding of Being is comprised as a definite characteristic… Therefore fundamental ontology, from which alone all other ontologies can take their rise, must be sought in the existential analytic of Dasein. (Being and Time 3: 33–4)

It is important to stress here that, in Heidegger's eyes, this prioritizing of Dasein does not lead to (what he calls) “a vicious subjectivizing of the totality of entities” (Being and Time 4: 34). This resistance towards any unpalatable anti-realism is an issue to which we shall return.

Dasein is, then, our primary ‘object’ of study, and our point of investigative departure is Dasein's everyday encounters with entities. But what sort of philosophical method is appropriate for the ensuing examination? Famously, Heidegger's adopted method is a species of phenomenology. In the Heideggerian framework, however, phenomenology is not to be understood (as it sometimes is) as the study of how things merely appear in experience. Rather, in a recognizably Kantian staging of the idea, Heidegger follows Husserl (1913/1983) in conceiving of phenomenology as a theoretical enterprise that takes ordinary experience as its point of departure, but which, through an attentive and sensitive examination of that experience, aims to reveal the a priori, transcendental conditions that shape and structure it. In Heidegger's Being-centred project, these are the conditions “which, in every kind of Being that factical Dasein may possess, persist as determinative for the character of its Being” (Being and Time 5: 38). Presupposed by ordinary experience, these structures must in some sense be present with that experience, but they are not simply available to be read off from its surface, hence the need for disciplined and careful phenomenological analysis to reveal them as they are. So far so good. But, in a departure from the established Husserlian position, one that demonstrates the influence of Dilthey, Heidegger claims that phenomenology is not just transcendental, it is hermeneutic (for discussion, see e.g., Caputo 1984, Kisiel 2002 chapter 8). In other words, its goal is always to deliver an interpretation of Being, an interpretation that, on the one hand, is guided by certain historically embedded ways of thinking (ways of taking-as reflected in Dasein's preontological understanding of Being) that the philosopher as Dasein and as interpreter brings to the task, and, on the other hand, is ceaselessly open to revision, enhancement and replacement. For Heidegger, this hermeneutic structure is not a limitation on understanding, but a precondition of it, and philosophical understanding (conceived as fundamental ontology) is no exception. Thus Being and Time itself has a spiral structure in which a sequence of reinterpretations produces an ever more illuminating comprehension of Being. As Heidegger puts it later in the text:

What is decisive is not to get out of the circle but to come into it the right way… In the circle is hidden a positive possibility of the most primordial kind of knowing. To be sure, we genuinely take hold of this possibility only when, in our interpretation, we have understood that our first, last and constant task is never to allow our fore-having, fore-sight and fore-conception to be presented to us by fancies and popular conceptions, but rather to make the scientific theme secure by working out these fore-structures in terms of the things themselves. (Being and Time 32: 195)

On the face of it, the hermeneutic conception of phenomenology sits unhappily with a project that aims to uncover the a priori transcendental conditions that make possible particular modes of Being (which is arguably one way of glossing the project of “working out [the] fore-structures [of understanding] in terms of the things themselves”). And this is a tension that, it seems fair to say, is never fully resolved within the pages of Being and Time. The best we can do is note that, by the end of the text, the transcendental has itself become historically embedded. More on that below. What is also true is that there is something of a divide in certain areas of contemporary Heidegger scholarship over whether one should emphasize the transcendental dimension of Heidegger's phenomenology (e.g., Crowell 2001, Crowell and Malpas 2007) or the hermeneutic dimension (e.g., Kisiel 2002).

2.2.2 Modes of Encounter
How, then, does the existential analytic unfold? Heidegger argues that we ordinarily encounter entities as (what he calls) equipment, that is, as being for certain sorts of tasks (cooking, writing, hair-care, and so on). Indeed we achieve our most primordial (closest) relationship with equipment not by looking at the entity in question, or by some detached intellectual or theoretical study of it, but rather by skillfully manipulating it in a hitch-free manner. Entities so encountered have their own distinctive kind of Being that Heidegger famously calls readiness-to-hand. Thus:

The less we just stare at the hammer-thing, and the more we seize hold of it and use it, the more primordial does our relationship to it become, and the more unveiledly is it encountered as that which it is—as equipment. The hammering itself uncovers the specific ‘manipulability’ of the hammer. The kind of Being which equipment possesses—in which it manifests itself in its own right—we call ‘readiness-to-hand’. (Being and Time 15: 98)

Readiness-to-hand has a distinctive phenomenological signature. While engaged in hitch-free skilled activity, Dasein has no conscious experience of the items of equipment in use as independent objects (i.e., as the bearers of determinate properties that exist independently of the Dasein-centred context of action in which the equipmental entity is involved). Thus, while engaged in trouble-free hammering, the skilled carpenter has no conscious recognition of the hammer, the nails, or the work-bench, in the way that one would if one simply stood back and thought about them. Tools-in-use become phenomenologically transparent. Moreover, Heidegger claims, not only are the hammer, nails, and work-bench in this way not part of the engaged carpenter's phenomenal world, neither, in a sense, is the carpenter. The carpenter becomes absorbed in his activity in such a way that he has no awareness of himself as a subject over and against a world of objects. Crucially, it does not follow from this analysis that Dasein's behaviour in such contexts is automatic, in the sense of there being no awareness present at all, but rather that the awareness that is present (what Heidegger calls circumspection) is non-subject-object in form. Phenomenologically speaking, then, there are no subjects and no objects; there is only the experience of the ongoing task (e.g., hammering).

Heidegger, then, denies that the categories of subject and object characterize our most basic way of encountering entities. He maintains, however, that they apply to a derivative kind of encounter. When Dasein engages in, for example, the practices of natural science, when sensing takes place purely in the service of reflective or philosophical contemplation, or when philosophers claim to have identified certain context-free metaphysical building blocks of the universe (e.g., points of pure extension, monads), the entities under study are phenomenologically removed from the settings of everyday equipmental practice and are thereby revealed as fully fledged independent objects, that is, as the bearers of certain context-general determinate or measurable properties (size in metres, weight in kilos etc.). Heidegger calls this mode of Being presence-at-hand, and he sometimes refers to present-at-hand entities as ‘Things’. With this phenomenological transformation in the mode of Being of entities comes a corresponding transformation in the mode of Being of Dasein. Dasein becomes a subject, one whose project is to explain and predict the behaviour of an independent, objective universe. Encounters with the present-at-hand are thus fundamentally subject-object in structure.

The final phenomenological category identified during the first phase of the existential analytic is what Heidegger calls un-readiness-to-hand. This mode of Being of entities emerges when skilled practical activity is disturbed by broken or malfunctioning equipment, discovered-to-be-missing equipment, or in-the-way equipment. When encountered as un-ready-to-hand, entities are no longer phenomenologically transparent. However, they are not yet the fully fledged objects of the present-at-hand, since their broken, malfunctioning, missing or obstructive status is defined relative to a particular equipmental context. The combination of two key passages illuminates this point: First:

[The] presence-at-hand of something that cannot be used is still not devoid of all readiness-to-hand whatsoever; equipment which is present-at-hand in this way is still not just a Thing which occurs somewhere. The damage to the equipment is still not a mere alteration of a Thing—not a change of properties which just occurs in something present-at-hand. (Being and Time 16: 103)

And second:

When something cannot be used—when, for instance, a tool definitely refuses to work—it can be conspicuous only in and for dealings in which something is manipulated. (Being and Time 68: 406)

Thus a driver does not encounter a punctured tyre as a lump of rubber of measurable mass; she encounters it as a damaged item of equipment, that is, as the cause of a temporary interruption to her driving activity. With such disturbances to skilled activity, Dasein emerges as a practical problem solver whose context-embedded actions are directed at restoring smooth skilled activity.

Although Heidegger does not put things this way, the complex intermediate realm of the un-ready-to-hand is seemingly best thought of as a spectrum of cases characterized by different modes and degrees of engagement/disengagement. Much of the time Dasein's practical problem solving will involve recovery strategies (e.g., switching to a different mode of transport) which preserve the marks of fluid and flexible know-how that are present in ready-to-hand contexts. In the limit, however (e.g., when a mechanic uses his theoretical knowledge of how cars work to guide a repair), Dasein's problem solving activity will begin to approximate the theoretical reasoning distinctive of scientific inquiry into present-at-hand entities. But even here Dasein is not ‘just theorizing’ or ‘just looking’, so it is not yet, in Heidegger's terms, a pure disengaged subject. With this spectrum of cases in view, it is possible to glimpse a potential worry for Heidegger's account. Cappuccio and Wheeler (2010; see also Wheeler 2005, 143) argue that the situation of wholly transparent readiness-to-hand is something of an ideal state. Skilled activity is never (or very rarely) perfectly smooth. Moreover, minimal subjective activity (such as a nonconceptual awareness of certain spatially situated movements by my body) produces a background noise that never really disappears. Thus a distinction between Dasein and its environment is, to some extent, preserved, and this distinction arguably manifests the kind of minimal subject-object dichotomy that is characteristic of those cases of un-readiness-to-hand that lie closest to readiness-to-hand.
  `,


  image: images['img1.jpg']
};

export default post1;
